# --- NEXUS_AI_SYSTEM/05_SELF_IMPROVEMENT_ENGINE/rewriting/code_rewriter.py ---

import ast
from typing import List, Dict

class CodeRewriter(ast.NodeTransformer):
    """
    A class for performing automated code refactoring and rewriting.

    This class uses Python's Abstract Syntax Tree (AST) module to parse,
    analyze, and modify the source code in a structured and safe way.
    It is the engine that will apply the suggestions generated by the
    KnowledgeSynthesizer.
    """

    def __init__(self, modifications: List[Dict]):
        """
        Initializes the rewriter with a list of modification tasks.

        Args:
            modifications (List[Dict]): A list of dictionaries, where each specifies a
                                       rewriting task, e.g., renaming a function,
                                       replacing a block, etc.
        """
        self.modifications = modifications

    def visit_FunctionDef(self, node: ast.FunctionDef):
        """
        Visits a function definition in the AST.
        """
        for mod in self.modifications:
            if mod['type'] == 'rename_function' and node.name == mod['old_name']:
                print(f"- Renaming function '{node.name}' to '{mod['new_name']}'")
                node.name = mod['new_name']
        return self.generic_visit(node)

    def rewrite_code(self, source_code: str) -> str:
        """
        Parses the source code into an AST, applies the transformations,
        and unparses it back into modified source code.

        Args:
            source_code (str): The original Python source code.

        Returns:
            str: The modified Python source code.
        
        Raises:
            SyntaxError: If the source code is not valid Python.
        """
        print("\n--- Rewriting code using AST... ---")
        try:
            tree = ast.parse(source_code)
            self.visit(tree)
            ast.fix_missing_locations(tree) # Important for unparsing
            return ast.unparse(tree)
        except SyntaxError as e:
            print(f"Error parsing source code: {e}")
            raise

if __name__ == '__main__':
    print("--- Running Code Rewriter Example ---")

    # 1. Original source code
    original_code = '''
def old_function_name():
    """This is a docstring."""
    print("Hello from the old function!")

class MyClass:
    def another_function(self):
        pass
'''

    # 2. Define the modification task
    # This would typically come from the KnowledgeSynthesizer
    mods_to_apply = [
        {
            'type': 'rename_function',
            'old_name': 'old_function_name',
            'new_name': 'new_and_improved_function'
        }
    ]

    # 3. Initialize and run the rewriter
    rewriter = CodeRewriter(modifications=mods_to_apply)
    
    print("--- Original Code ---")
    print(original_code)
    
    modified_code = rewriter.rewrite_code(original_code)
    
    print("\n--- Modified Code ---")
    print(modified_code)

    # Verify the change
    assert "new_and_improved_function" in modified_code
    assert "old_function_name" not in modified_code
    print("\nCode rewriting successful.")
